# created by eselect-repo

[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git

[gentoo-zh]
location = /var/db/repos/gentoo-zh
sync-type = git
sync-uri = https://github.com/gentoo-mirror/gentoo-zh.git


[simonvanderveldt]
location = /var/db/repos/simonvanderveldt
sync-type = git
sync-uri = https://github.com/gentoo-mirror/simonvanderveldt.git

[tatsh-overlay]
location = /var/db/repos/tatsh-overlay
sync-type = git
sync-uri = https://github.com/gentoo-mirror/tatsh-overlay.git


[mv]
location = /var/db/repos/mv
sync-type = git
sync-uri = https://github.com/gentoo-mirror/mv

[x0rzavi]
location = /var/db/repos/x0rzavi
sync-type = git
sync-uri = https://github.com/gentoo-mirror/x0rzavi.git

[src_prepare-overlay]
location = /var/db/repos/src_prepare-overlay
sync-type = git
sync-uri = https://github.com/gentoo-mirror/src_prepare-overlay.git


[pppig]
location = /var/db/repos/pppig
sync-type = git
sync-uri = https://github.com/PIPIPIG233666/gentoo_pppig

[steam-overlay]
location = /var/db/repos/steam-overlay
sync-type = git
sync-uri = https://github.com/gentoo-mirror/steam-overlay.git

[ryans]
location = /var/db/repos/ryans
sync-type = git
sync-uri = https://github.com/gentoo-mirror/ryans.git

[HomeAssistantRepository]
location = /var/db/repos/HomeAssistantRepository
sync-type = git
sync-uri = https://github.com/gentoo-mirror/HomeAssistantRepository.git

[lmiphay]
location = /var/db/repos/lmiphay
sync-type = git
sync-uri = https://github.com/gentoo-mirror/lmiphay.git

[xira]
location = /var/db/repos/xira
sync-type = git
sync-uri = https://github.com/gentoo-mirror/xira.git

[pf4public]
location = /var/db/repos/pf4public
sync-type = git
sync-uri = https://github.com/PF4Public/gentoo-overlay

[hyprland-overlay]
location = /var/db/repos/hyprland-overlay
sync-type = git
sync-uri = https://github.com/gentoo-mirror/hyprland-overlay.git

[xarblu-overlay]
location = /var/db/repos/xarblu-overlay
sync-type = git
sync-uri = https://github.com/gentoo-mirror/xarblu-overlay.git
