#!/usr/bin/env bash
# Make it executable (chmod +x) for Portage to process it.
# Requires sys-apps/pkgcore for pmaint

# Your hook can control it's actions depending on any of the three
# parameters passed in to it.
#
# They are as follows:
#
# The repository name.
repository_name=${1}
# The URI to which the repository was synced.
sync_uri=${2}
# The path to the repository.
repository_path=${3}

# Portage assumes that a hook succeeded if it exits with 0 code. If no
# explicit exit is done, the exit code is the exit code of last spawned
# command. Since our script is a bit more complex, we want to control
# the exit code explicitly.
ret=0

if [[ -n "${repository_name}" ]]; then
	# Repository name was provided, so we're in a post-repository hook.
	echo "* In post-repository hook for ${repository_name}"
	echo "** synced from remote repository ${sync_uri}"
	echo "** synced into ${repository_path}"

	# Gentoo, Guru, kde and science come with pregenerated cache but the other repositories usually don't.
	# Generate them to improve performance.
	# https://www.gentoo.org/support/news-items/2025-10-07-cache-enabled-mirrors-removal.html
	if [[ "${repository_name}" != "gentoo" ]] && [[ "${repository_name}" != "guru" ]] && \
		[[ "${repository_name}" != "kde" ]] && [[ "${repository_name}" != "science" ]]
	then
		if ! pmaint regen "${repository_name}" --threads $(nproc) --pkg-desc-index --use-local-desc ${PORTAGE_VERBOSE+--verbose}
		then
			echo "!!! pmaint regen failed!"
			ret=1
		fi
	fi
fi

exit "${ret}"

